flows:
  - summary: Invoice seller main flow
    id: invoice-loan-seller-flow-1
    shouldDispaly: true
    version:
      - 2.0.0
      - 2.1.0
    input:
      $ref: ./invoice-loan-flow-1-seller/input.yaml
    calls:
      $ref: ./invoice-loan-flow-1-seller/protocolCalls.yaml
    config_selector:
      $ref: ./invoice-loan-flow-1-seller/selector.yaml
