on_settle:
  message:
  collector_app_id: collectorapp.com
  receiver_app_id: receiverapp.com
  settlement:
    type: NP-NP
    id: settlement-id-abc
    orders:
    - id: ordr-123456
      inter_participant:
        settled_amount:
          currency: INR
          value: '1000.00'
        amount:
          currency: INR
          value: '1000.12'
        status: SETTLED
        reference_no: '3245683618631'
      collector:
        amount:
          currency: INR
          value: '50.00'
      self:
        amount:
          currency: INR
          value: '50.00'
        status: SETTLED
        reference_no: '1238683618634'

on_report:
  message:
  collector_app_id: collectorapp.com
  receiver_app_id: receiverapp.com
  settlement:
    type: NP-NP
    id: settlement-id-123
    orders:
    - id: order-id-456
      inter_participant:
        settled_amount:
          currency: INR
          value: '1000.00'
        amount:
          currency: INR
          value: '1000.27'
        status: SETTLED
        reference_no: '3718683618631'
        error:
          code: '01'
          message: Account Inactive
      collector:
        amount:
          currency: INR
          value: '50.00'
      provider:
        id: provider-id-789
        amount:
          currency: INR
          value: '800.00'
        status: NOT-SETTLED
        error:
          code: '01'
          message: Account Inactive
        reference_no: '3718683618634'
      self:
        amount:
          currency: INR
          value: '200.00'
        status: NOT-SETTLED
        reference_no: '3718683618634'
        error:
          code: '01'
          message: Account inactive

on_recon:
  message:
  orders:
  - id: string
    amount:
      currency: INR
      value: ''
    recon_accord: true
    settlements:
    - id: string
      payment_id: string
      status: string
      amount:
        diff_value: string
        currency: INR
        value: ''
      commission:
        diff_value: string
        currency: INR
        value: ''
      withholding_amount:
        diff_value: string
        currency: INR
        value: ''
      tcs:
        diff_value: string
        currency: INR
        value: ''
      tds:
        diff_value: string
        currency: INR
        value: ''
      updated_at: '2024-09-17T14:51:35.289Z'
      settlement_ref_no: string
