search:
  default:
    config: search2_station-code
  search1_station-code: 
    config: search
    condition:
      operation:
        type: AND
        input:
          value:
            - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.message.intent.fulfillment.stops"
                    - "undefined"



select:
  default:
    config: select

init: 
  default:
    config: init

confirm: 
  default:
    config: confirm

update: 
  default:
    config: update

status: 
  default:
    config: status

cancel: 
  default:
    config: cancel
  cancel-confirm: 
    config: cancel_confirm
    condition:
      operation:
        type: AND
        input:
          value:
            - operation:
                type: EQUAL
                title: Check search message code
                input:
                  value:
                    - operation:
                        type: READ
                        input:
                          value: "req_body.message.descriptor.code"
                    - "CONFIRM_CANCEL"