issue:
  type: "issue"
  category: "reciever"
  target: "NP"
  executed: false
  shouldRender: true
  config: "issue" #name of the call
  nextRequest: "on_issue"
  preRequest: issue
  isCollapsed: false
  current: issue
  # default_payload:
  #   $ref: ./default_payload.yaml#/settle

on_issue:
  type: "on_issue"
  category: "sender"
  target: "NP"
  executed: false
  shouldRender: true
  config: "on_issue" #name of the call
  nextRequest: "on_issue"
  preRequest: issue
  isCollapsed: false
  current: on_issue

