# filename = output json name 
# domain = path argument
# path = data read from configs

configs:
  - filename : trv_build.json
    domain: trv 
    path : 
      $ref: ./trv/trv.yaml
  - filename : fis_build.json
    domain: fis 
    path : 
      $ref: ./fis/fis.yaml
  - filename : nts_build.json
    domain: nts 
    path : 
      $ref: ./nts/index.yaml
